### ISSUE TITLE
docs example for `import/named` errors in imports from third-party libraries doesn't work

### ISSUE THREAD

**Issue by MustafaHaddara** [import-js/eslint-plugin-import#2163]
`import/named` describes a few examples with 3rd party libraries, specifically with React and Redux. 

However, I attempted to reproduce the example in a [fresh create-react-app project](https://github.com/MustafaHaddara/eslint-plugin-import-repro/commit/6c371fa87cf04704c5c8ec462669597e5a360dd2), and it didn't flag anything wrong with my imports from redux. 

Redux doesn't have a `jsnext:main` key in its `package.json`, and the [link to the `rollup` wiki in the further reading section of the docs](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md#further-reading) is dead. `jsnext:main` is [deprecated](https://github.com/jsforum/jsforum/issues/5) in favour of [`pkg.module`](https://github.com/rollup/rollup/wiki/pkg.module), but Redux ships with a `pkg.module` definition and yet `import/named` doesn't catch bad imports from redux.

What's the correct way to configure this plugin to report non-existent named imports from third party libraries?

**Comment by ljharb** [comment]
Looks like these examples all need updating.

I doubt we look at the nonstandard "module" field; that's not a real thing (neither is `jsnext:main`, of course, but support for that predates my involvement here).

Redux 4's "main" is https://unpkg.com/browse/redux@4.1.0/lib/redux.js, which is CJS, but has (conceptually) 5 meaningful named exports:
 - applyMiddleware
 - bindActionCreators
 - combineReducers
 - compose
 - createStore

It's likely that since we don't support "module", and this package, according to node, has nothing but a single CJS file, that there's no way we can check this currently.

**Comment by MustafaHaddara** [comment]
Thanks for the quick response!

Are you aware of any other eslint plugins that can lint imports from third-party libraries?

**Comment by ljharb** [comment]
As far as I know of, this is the only package that lints imports and looks at other files at all.

Since we do support jsnext:main, and since major packages have dropped it in favor of "module", i'd be willing to review a PR that added support for it.

**Comment by MustafaHaddara** [comment]
I've opened a draft PR [here](https://github.com/import-js/eslint-plugin-import/pull/2166) (still needs tests), let me know if you think i'm looking in the entirely wrong direction or what. I'm also not sure how to manually test it. 

Would love to get your thoughts, thanks.
