### ISSUE TITLE
[Feature request] Add exports-first rule (opposite of exports-last)

### ISSUE THREAD

**Issue by C0ZEN** [import-js/eslint-plugin-import#2242]
Is there an opposite to https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/exports-last.md to ensure that every export is actually at the beginning?
If not, I would like to provide a PR which bring this possibility, if you don't see any reason to not do this.

**Comment by ljharb** [comment]
There's no technical reason not to do it.

The non-technical reasons include that it's not a common style in the ecosystem, because it requires relying on hoisting, and this is widely considered a bad pattern. I personally would never use this style, and would consider code that does to be hard to understand - just like if `return` was at the top of a function.

Can you help me understand why this is something you want?

**Comment by C0ZEN** [comment]
**Context:**
Basically, we have in a company project some rules to order in classes the properties per visibility: putting public on top and private at the bottom.
The only reason behind this is to have a “faster” access to the public code and to avoid scrolling to less important code.
A question was raised regarding the “strange” reversed logic regarding the export being at the bottom and the none-exported stuff at the top (could be considered like private first, then public).
So, only sugar and cool for scroll haters ;)
But I found the point good enough to wonder: why not if it works? Hence, my question.

**Comment by ljharb** [comment]
module exports are like function returns - most people expect to find them at the bottom.

JS doesn't really have "private" and "public" - it only has "reachable" or "non-reachable", so i think it's a mindset issue more than anything else.

**Comment by C0ZEN** [comment]
OK, then thank you for the advices, I will spread the word and close this one ;)
Thank you for the swift response, BTW!
