### ISSUE TITLE
Unable to resolve path to module 'unbuild'.

### ISSUE THREAD

**Issue by Plasticine-Yang** [import-js/eslint-plugin-import#2620]
I have an error - Unable to resolve path to module 'unbuild'.

I encountered this error when trying to import the package 'unbuild', but it is normal to import other packages.

Could you please check it?

My files:

package.json

```json
{
  "name": "@plasticine-yang/eslint-config-basic-playground",
  "version": "0.0.0",
  "type": "module",
  "private": true,
  "packageManager": "pnpm@7.1.0",
  "author": "Plasticine-Yang",
  "license": "MIT",
  "devDependencies": {
    "@plasticine-yang/eslint-config-basic": "workspace:*",
    "unbuild": "^1.0.2"
  }
}
```

.eslintrc.cjs

```js
/** @type { import('eslint').ESLint.ConfigData } */
module.exports = {
  env: {
    es6: true,
    browser: true,
    node: true,
  },

  extends: ['eslint:recommended', 'plugin:import/recommended'],

  settings: {
    'import/resolver': {
      node: { extensions: ['.js', '.cjs', '.mjs'] },
    },
  },
}
```

![image](https://user-images.githubusercontent.com/63829979/209497616-010928d6-1fe5-467b-8794-f7be0a326b24.png)

**Comment by ljharb** [comment]
The issue here is that this package doesn't specify a "main", only "exports", which makes it not backwards-compatible.

This plugin uses `resolve`, which does not yet support `exports`, so it's not yet capable of resolving this package.

Eventually, `resolve` will support it, but a better solution is for `unbuild` to support pre-exports nodes by supplying a "main".
