### ISSUE TITLE
Using Typescript 5.0's array extends in tsconfig causes an error while linting

### ISSUE THREAD

**Issue by NutchapolSal** [import-js/eslint-plugin-import#2751]
Typescript 5.0 now supports combining TSConfigs using array syntax in `extends`

Error log:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
Occurred while linting G:\gits\NutchapolSal\musicbot\botCacheInit.js:1
Rule: "import/namespace"
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:429:7)
    at loadTsconfig (G:\gits\NutchapolSal\musicbot\node_modules\tsconfig-paths\lib\tsconfig-loader.js:93:39)
    at loadSyncDefault (G:\gits\NutchapolSal\musicbot\node_modules\tsconfig-paths\lib\tsconfig-loader.js:40:18)
    at tsConfigLoader (G:\gits\NutchapolSal\musicbot\node_modules\tsconfig-paths\lib\tsconfig-loader.js:26:22)
    at readTsConfig (G:\gits\NutchapolSal\musicbot\node_modules\eslint-plugin-import\lib\ExportMap.js:804:521)
    at isEsModuleInterop (G:\gits\NutchapolSal\musicbot\node_modules\eslint-plugin-import\lib\ExportMap.js:806:277)
    at ExportMap.parse (G:\gits\NutchapolSal\musicbot\node_modules\eslint-plugin-import\lib\ExportMap.js:798:233)
    at ExportMap.for (G:\gits\NutchapolSal\musicbot\node_modules\eslint-plugin-import\lib\ExportMap.js:797:201)
```

This also effects `import/namespace`, `import/named`, `import/default`, `import/no-named-as-default`, and `import/no-named-as-default-member`.

**Comment by ljharb** [comment]
tsconfig-paths doesn't support this yet, and even if they added that support, they'd need to backport it to v3 for us to be able to use it.

**Comment by WoodyWoodsta** [comment]
See https://github.com/dividab/tsconfig-paths/pull/245, which was released in `tsconfig-paths` v4. Either:
1. `tsconfig-paths` backports support to v3, or
2. `eslint-plugin-import` upgrades `tsconfig-paths` to v4

I'm unable to find what the breaking changes are in v4, so I don't know how much of an issue it would be to upgrade in this package.

**Comment by WoodyWoodsta** [comment]
Perhaps:

> Ignore --project/-P CLI flag when explicit options are passed to register

If this is the only breaking change in `tsconfig-paths` I don't see why this is a problem for this project, since it should not be concerned about `tsconfig-path`'s CLI

**Comment by ljharb** [comment]
@WoodyWoodsta its a nonstarter, see #2447, so hopefully they go with option 1.

**Comment by WoodyWoodsta** [comment]
Ouch - not to bring that discussion over here, but maintaining Node v4 support is not something I've come across before. That is your decision though, but I don't think that `tsconfig-paths` has any obligation to backport to v3 given the fix is for new major releases of a tool. It would be nice, but I'd expect the support for TS 5 to be limited to `tsconfig-paths` v4.

**Comment by ljharb** [comment]
Nobody has any obligation to do anything :-) i think their v4 platform drop was a mistake, and another park forward is for v4 to restore node 4 support (which it could do in a semver minor).

If tsconfig-paths maintainers would accept a PR restoring that support, I’d be happy to author it, so this plugin could update to v4.

**Comment by WoodyWoodsta** [comment]
> If tsconfig-paths maintainers would accept a PR restoring that support, I’d be happy to author it, so this plugin could update to v4.

@ljharb Open an issue then.

**Comment by ljharb** [comment]
Yep, that’s indeed the kind of entitlement and laziness that explains why forks aren’t sustainable.

**Comment by WoodyWoodsta** [comment]
I'm not sure I understand?

**Comment by ljharb** [comment]
It’s something you want, and I’ve given you a path to getting what you want - and instead of you just filing the issue, you said “psh, you do it”.

**Comment by WoodyWoodsta** [comment]
I think that's the misunderstanding. It's the decision you've made, as is your full right, but still **your** decision, not mine. You have a PR open with 90+ comments, 25 participants all of whom are **not** in support of your proposition. So no, I don't think I'm practicing any entitlement or laziness. Rather, I've spent a fair amount of time attempting to guide you towards a different perspective which, as unbelievable as it appears to you, is not an unreasonable perspective and is in the interest of the community you lead. 🤷

I'm not really interested in putting any further effort into this sort of a cause. My organisation will see if `eslint-plugin-i` is suitable, otherwise we'll forfeit linting imports altogether.

**Comment by ljharb** [comment]
Good luck to you.

**Comment by knpwrs** [comment]
Adding this to my `package.json` resolves the issue for me:

```json
  "overrides":{
    "tsconfig-paths": "^4.0.0"
  }
```

**Comment by yorch** [comment]
For yarn it would be `resolutions` like:

```json
  "resolutions":{
    "tsconfig-paths": "^4.0.0"
  }
```

**Comment by ljharb** [comment]
Using overrides/resolutions is a perfectly reasonable approach, assuming the breaking changes don't affect our usage of the package.

**Comment by so1ve** [comment]
For those who suffer from this problem, I recommend eslint-plugin-i. It uses get-tsconfig instead of tsconfig-paths, which may fix this issue.

**Comment by so1ve** [comment]
@ljharb You marked my solution as spam? WTF I just provided a VIABLE solution. As the leader of such a large community, we, as users, are grateful for your contributions to eslint. However, what you have done is chilling.

**Comment by ljharb** [comment]
@so1ve switching to a different project isn’t a solution, so yes, it’s spam.

**Comment by mlippert** [comment]
@ljharb I agree with @so1ve that his comment is NOT SPAM, and is a viable solution for people running into the problem. I understand you don't want to fix the issue as is your right, but I felt I should also speak up that marking his comment as spam is not correct and needlessly aggressive.

**Comment by ljharb** [comment]
@mlippert your agreement is irrelevant; advertising another project in a project is spam anywhere i make the decisions. It is thus quite correct, and far less aggressive than suggesting people use a competitor.

**Comment by NutchapolSal** [comment]
well, yours doesn't work right so using a competitor is the only thing to do. have you tried actually fixing the problem for real users of current version software?

**Comment by WoodyWoodsta** [comment]
Advertising? 🤔

**Comment by so1ve** [comment]
Your plugin doesn't work, so even I don't want to use a competitor project, **I HAD NO CHOICE BUT TO DO SO**. Why don't you use tslint? Because it is outdated. So, as a user, why not use a smaller and less buggy project? I'm not the author of eslint-plugin-import nor eslint-plugin-i, I'm just a user of them. I just want to solve my problem, **I DON'T CARE WHETHER THEY ARE COMPETITORS**. I just want to help those who also suffer from this problem.

Of course, you are going to mark my comment as "spam". Just go ahead, I don't care.
