### ISSUE TITLE
Semver metavuln

### ISSUE THREAD

**Issue by Adam-Ignjatovic** [import-js/eslint-plugin-import#2804]
Please bump your semver version.

**Comment by ljharb** [comment]
Like most CVEs, it's a false positive. We're not using `new Range` nor are we doing anything that wouldn't be a self-attack (ie, not an attack).

We can't ever bump the semver version because v7 drops support for engines we support, so unless the fix is backported to v6, it'll just have to remain a false positive.

Duplicate of #2803.
