### ISSUE TITLE
semver vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by stantalid** [import-js/eslint-plugin-import#2807]
There is an [advisory](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) for the `semver` package that is a dependency.

Could you please update the dependecy to solve the issue?

**Comment by ljharb** [comment]
Like most CVEs, it's a false positive. We're not using `new Range` nor are we doing anything that wouldn't be a self-attack (ie, not an attack).

We can't ever bump the semver version because v7 drops support for engines we support, so unless the fix is backported to v6, it'll just have to remain a false positive.

Duplicate of #2803. Duplicate of #2804. Duplicate of #2805. Duplicate of #2806.
