### ISSUE TITLE
Address security vulnerability of semver@v7.5.1

### ISSUE THREAD

**Issue by ravijayaramappa** [import-js/eslint-plugin-import#2821]
semver v7.5.1 and older have a security vulnerability https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795. Please update to semver@v7.5.2 or newer

**Comment by ljharb** [comment]
Like most CVEs, it's a false positive. We're not using `new Range` nor are we doing anything that wouldn't be a self-attack (ie, not an attack).

We can't ever bump the semver version because v7 drops support for engines we support, so unless the fix is backported to v6, it'll just have to remain a false positive.

Duplicate of #2803. Duplicate of #2804. Duplicate of #2805. Duplicate of #2806. Duplicate of #2807. Duplicate of #2808. Duplicate of #2809. Duplicate of #2814.
