### ISSUE TITLE
NPM audit fails due to vulnerability in semver

### ISSUE THREAD

**Issue by restfulhead** [import-js/eslint-plugin-import#2822]
Report:

```
semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
```

Suggested fix: Update `semver` to `7.5.3`

**Comment by ljharb** [comment]
Like most CVEs, it's a false positive. We're not using `new Range` nor are we doing anything that wouldn't be a self-attack (ie, not an attack).

We can't ever bump the semver version because v7 drops support for engines we support, so unless the fix is backported to v6, it'll just have to remain a false positive.

Duplicate of #2803. Duplicate of #2804. Duplicate of #2805. Duplicate of #2806. Duplicate of #2807. Duplicate of #2808. Duplicate of #2809. Duplicate of #2814. Duplicate of #2821.

**Comment by KenjiTakahashi** [comment]
FYI: Babel is now using their own fork of semver 6: https://github.com/babel/babel/pull/15742

**Comment by ljharb** [comment]
That's an extreme path I'd prefer not to take.
