### ISSUE TITLE
`parserOptions` shouldn't be in recommended config

### ISSUE THREAD

**Issue by dword-design** [import-js/eslint-plugin-import#2868]
I think the `parserOptions` options are part of the ESLint config extending from `eslint-plugin-import` or they should be set to the latest `ecmaVersion`. Using the recommended config leads to errors parsing new JS features like optional chaining.

**Comment by ljharb** [comment]
They definitely should be there, and if you want to set your own parserOptions, that would always be happening *after* extending configs, so it shouldn't cause any errors.

**Comment by jaydenseric** [comment]
No @ljharb he's right; it's incorrect to set `parserOptions.sourceType` to `"module"` for every linted file, including `.cjs` files which are always CJS and, if the project `package.json` has `type` set to `"commons"` (which is the default!) `.js` files are also CJS.

Less concerning, but setting `ecmaVersion: 2018` also seems like it should not be the concern of this particular plugin as `ecmaVersion` relates to more things than just ESM syntax. Only the user configuring their project can know the intended ECMA version for their codebase. It's not good this plugin's recommended config downgrades an ECMA version higher than 2018 that may have been set by other ESLint configs.

**Comment by ljharb** [comment]
Order of config extends matters, and the end user should be setting these things anyways.

Separately, i don’t recommend using the recommended config from any eslint plugin, including this one - semver constraints mean it’s almost always not in an ideal state. You should be using this plugin via the Airbnb config.

**Comment by ljharb** [comment]
No, that’s not correct; it’s needed for eslint itself and parsers.

We don’t yet support flat config.

**Comment by fullPendrive** [comment]
I believe that what @ghost tried to add to the discussion is a solution: currently, this ESLint plugin needs to read explicitly the lines "languageOptions.parserOptions.ecmaVersion" and "settings.'import/parsers'" in a ESLint config. Without these lines your plugin doesn't work. Meanwhile, other plugins don't need these lines to be declared in the config, although they may recommended it.

Your plugin could be rewritten to work without these lines explicitly declared in the config. In the scenario in which these lines are omitted in a custom ESLint config, instead of emitting an error, your plugin could provide a default value for these lines and proceed to analyze files.

This would contribute to solve the current issue.

**Comment by ljharb** [comment]
I'm not sure why both of those comments are from different deleted accounts - i smell LLM garbage, but can't be sure. Either way, I'm going to hide them all.
