### ISSUE TITLE
Update to tsconfig-paths package

### ISSUE THREAD

**Issue by KishoreKoushik** [import-js/eslint-plugin-import#2888]
Can we please have the package with the updated tsconfig-paths version. It seem to be two years old version and we see many vulnerabilities reported during our project publishing process

**Comment by ljharb** [comment]
Nope, because v4 drops support for engines that we support, so we can't ever upgrade past v3. Also, i'm not sure what vulnerabilities you mean; json5's vulnerability was fixed in v1 so it shouldn't be a problem.

Duplicate of #2447. Duplicate of #2660. Duplicate of #2625; a duplicate of #2628; a duplicate of #2626; a duplicate of #2627; a duplicate of #2631; a duplicate of #2632; a duplicate of #2634; a duplicate of #2635; a duplicate of #2636; a duplicate of #2637; a duplicate of #2639; a duplicate of #2642; a duplicate of #2643; a duplicate of #2649; a duplicate of #2655.

**Comment by KishoreKoushik** [comment]
yes json5 with version 1.0.1 has the vulnerability

**Comment by ljharb** [comment]
and v1.0.2 doesn’t, which you can update to yourself.
